[build]
    publish = "public"
    command = "make -C themes/prolotheme && hugo"

[build.environment]
    HUGO_VERSION = "0.140.2"

[context.deploy-preview]
    command = "make -C themes/prolotheme && hugo --buildDrafts"
